### ISSUE TITLE
Integrate support for other Arch sites

### ISSUE THREAD

**Issue by jmetrius** [MiAmigaAiva/firefox-aur-search#2]
Hey,

I found your plugin when looking for a way to replace the defunct arch-firefox-search AUR package (https://aur.archlinux.org/packages/arch-firefox-search/). Would you be interested in adding the search capabilities provided by that package to your plugin?

Best regards.

**Comment by jmetrius** [comment]
Nevermind, someone already did the work at https://github.com/noraj/firefox-extension-arch-search

**Comment by MiAmigaAiva** [comment]
I'm no longer involved with Arch Linux, and https://github.com/noraj/firefox-extension-arch-search is indeed the better option. :+1: 

I updated description directing users to get it instead & hid my AMO listing to help with discoverability.
